/* ----------------------------------------------------------
   SECTION 1: MULTIPLE SELECT STATEMENTS
   Requirement: Complex data retrieval using subqueries and filters
   ---------------------------------------------------------- */

-- Query A: Identify "High Value" customers who have spent more than $300 
-- Based on Script-2, this will capture users with the default $400 bookings
SELECT first_name, last_name, phone 
FROM Customers 
WHERE customer_id IN (
    SELECT customer_id 
    FROM Bookings 
    WHERE total_price > 300
);

-- Query B: Retrieve all currently active marketing promotions
-- Ensures the promotion is within its valid date range and marked active
SELECT promo_code, description, discount_percent, end_date 
FROM Promotions 
WHERE start_date <= CURRENT_DATE 
  AND end_date >= CURRENT_DATE 
  AND is_active = TRUE;

/* ----------------------------------------------------------
   SECTION 2: JOINS & CASE STATEMENTS
   Requirement: Different JOIN types and meaningful business data translation
   ---------------------------------------------------------- */

SELECT 
    c.first_name || ' ' || c.last_name AS customer_full_name,
    f.flight_code,
    b.total_price,
    -- Logic to translate internal status codes into user-friendly business terms
    CASE 
        WHEN b.status = 'Confirmed' THEN '✅ Trip Verified'
        WHEN b.status = 'Pending'   THEN '⏳ Awaiting Payment'
        WHEN b.status = 'Cancelled' THEN '❌ Booking Terminated'
        ELSE 'Status Unknown'
    END AS operational_status,
    -- Business logic for customer segmentation based on spending established in Script-2
    CASE 
        WHEN b.total_price >= 400 THEN 'VIP Priority Tier'
        ELSE 'Standard Service Tier'
    END AS service_segmentation
FROM Customers c
LEFT JOIN Bookings b ON c.customer_id = b.customer_id
LEFT JOIN Booking_Details bd ON b.booking_id = bd.booking_id
LEFT JOIN Flights f ON bd.flight_id = f.flight_id;

/* ----------------------------------------------------------
   SECTION 3: AGGREGATE FUNCTIONS & GROUPING
   Requirement: Statistical analysis for financial reporting
   ---------------------------------------------------------- */

-- Analyzes flight pricing data generated by the logic in Script-2
SELECT 
    seat_class,
    COUNT(*) AS total_available_flights,
    MIN(price_per_seat) AS entry_level_price,
    MAX(price_per_seat) AS premium_peak_price,
    ROUND(AVG(price_per_seat), 2) AS market_average_price
FROM Flights
GROUP BY seat_class
ORDER BY market_average_price DESC;

/* ----------------------------------------------------------
   SECTION 4: TCL & ACID PRINCIPLES (Demonstration)
   Requirement: Transaction Management and Atomicity testing
   ---------------------------------------------------------- */

-- Synchronizing sequences for PostgreSQL to prevent PK conflicts
SELECT setval('bookings_booking_id_seq', (SELECT COALESCE(MAX(booking_id), 1) FROM Bookings));
SELECT setval('loyalty_ledger_ledger_id_seq', (SELECT COALESCE(MAX(ledger_id), 1) FROM Loyalty_Ledger));

BEGIN; -- Manual transaction start

    -- 1. Insert a new booking record for Customer 1
    INSERT INTO Bookings (customer_id, status, total_price) 
    VALUES (1, 'Confirmed', 550.00);

    -- 2. Award loyalty points (10%) linked to the latest booking
    -- Note: 'balance' is automatically updated via GENERATED ALWAYS column
    INSERT INTO Loyalty_Ledger (customer_id, booking_id, points_earned)
    VALUES (1, (SELECT MAX(booking_id) FROM Bookings), 55);

    -- Verification step (Visible within the current session)
    SELECT * FROM Bookings WHERE booking_id = (SELECT MAX(booking_id) FROM Bookings);

COMMIT; -- Finalize changes

/* ----------------------------------------------------------
   SECTION 5: ACCESS LEVEL VIEWS
   Requirement: Simulation of Admin, Travel Agent, and Customer security roles
   ---------------------------------------------------------- */

-- Cleanup existing views to allow for structural updates
DROP VIEW IF EXISTS view_admin_report;
DROP VIEW IF EXISTS view_agent_operations;
DROP VIEW IF EXISTS view_customer_self;

-- 1. Admin View: High-level user and security oversight
CREATE VIEW view_admin_report AS 
SELECT user_id, email, role_id FROM Users;

-- 2. Travel Agent View: Operational contact data
CREATE VIEW view_agent_operations AS 
SELECT first_name, last_name, phone FROM Customers;

-- 3. Customer View: Personal booking history restricted to a single user
CREATE VIEW view_customer_self AS 
SELECT booking_date, status, total_price 
FROM Bookings 
WHERE customer_id = 1;

-- Verification of view outputs
SELECT * FROM view_admin_report;
SELECT * FROM view_agent_operations LIMIT 5;
SELECT * FROM view_customer_self;